-- In this file, write insert queries to populate the burgers table with at least three entries.
---------
-- Run the schema.sql and seeds.sql files into the mysql server from the command line
----------------------
-- BURGERS SEEDS -----
-- INSERT INTO burgers (name)
-- VALUE ("cheeseburger");
-- INSERT INTO burgers (name)
-- VALUE ("salad");
-- INSERT INTO burgers (name)
-- VALUE ("fries");
-- INSERT INTO burgers (devoured)
-- VALUE ("yes");
